package com.team64.BubbleFlowBackend.service;

import com.team64.BubbleFlowBackend.model.*;
import com.team64.BubbleFlowBackend.model.OrderSubmissionObject.DrinkWithToppings;
import com.team64.BubbleFlowBackend.repository.ExtraRepo;
import com.team64.BubbleFlowBackend.repository.OrderRepo;
import com.team64.BubbleFlowBackend.repository.OrderItemRepo;
import com.team64.BubbleFlowBackend.repository.OrderExtraRepo;
import com.team64.BubbleFlowBackend.repository.OrderItemRawRepo;
import com.team64.BubbleFlowBackend.repository.OrderExtraRawRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

@Service
public class OrderService {
    private final OrderRepo orderRepo;
    private final OrderItemRepo orderItemRepo;
    private final OrderExtraRepo orderExtraRepo;
    private final ExtraRepo extraRepo;
    private final OrderItemRawRepo orderItemRawRepo;
    private final OrderExtraRawRepo orderExtraRawRepo;

    @Autowired
    public OrderService(OrderRepo orderRepo, OrderItemRepo orderItemRepo, OrderExtraRepo orderExtraRepo, ExtraRepo extraRepo, OrderItemRawRepo orderItemRawRepo, OrderExtraRawRepo orderExtraRawRepo) {
        this.orderRepo = orderRepo;
        this.orderItemRepo = orderItemRepo;
        this.orderExtraRepo = orderExtraRepo;
        this.extraRepo = extraRepo;
        this.orderItemRawRepo = orderItemRawRepo;
        this.orderExtraRawRepo = orderExtraRawRepo;
    }

    public List<Order> getAllOrders(){
        return orderRepo.findAll();
    }

    public Order createOrder(Order order) {
        System.out.println("WARNING: CREATEORDER IS ONLY USED WITH PRE-CREATED ORDER OBJECTS");
        return orderRepo.save(order);
    }

    @Transactional
    public Order submitOrder(OrderSubmissionObject orderSubmissionObject) {
        // Create and populate the order
        System.out.println(orderSubmissionObject);

        Order order = new Order();
        order.setOrder_total_price(orderSubmissionObject.getTotalPrice());
        order.setCustomer(orderSubmissionObject.getCustomerName());
        order.setEmployee_id(orderSubmissionObject.getEmployeeId());
        order.setPayment_method(orderSubmissionObject.getPaymentMethod());
        order.setOrder_date(new Timestamp(System.currentTimeMillis()));

        // Save the order first to get its ID
        order = orderRepo.save(order);

        // Process drinks and add them to the order
        List<DrinkWithToppings> drinks = orderSubmissionObject.getDrinks();
        if (drinks != null) {
            for (DrinkWithToppings item : drinks) {
                OrderItemRaw orderItemRaw = new OrderItemRaw();
                orderItemRaw.setDrink_id(item.getDrink_id());
                orderItemRaw.setOrder_id(order.getOrderId()); // Ensure order_id is set
                //order_item_id generated by constructor

                // Save the order item to get its generated ID
                orderItemRaw = orderItemRawRepo.save(orderItemRaw);
                int orderItemID = orderItemRaw.getOrder_item_id();

                // Process toppings
                for (int toppingID : item.getToppings()) {
                    // Get the Extra entity
                    // Extra extra = extraRepo.findById(toppingID)
                    //         .orElseThrow(() -> new RuntimeException("Extra not found with id: " + toppingID));

                    // Create OrderExtra and set relationships
                    OrderExtraRaw orderExtraRaw = new OrderExtraRaw();
                    orderExtraRaw.setOrder_item_id(orderItemID);
                    orderExtraRaw.setExtras_id(toppingID);

                    orderExtraRawRepo.save(orderExtraRaw);
                }
            }
        }

        // Fetch the complete order with all its items and extras
        return orderRepo.findById(order.getOrderId()).orElse(order);
    }

    @Transactional
    public OrderItem addExtraToOrderItem(int orderItemId, int extraId) {
        OrderItem orderItem = orderItemRepo.findById(orderItemId)
                .orElseThrow(() -> new RuntimeException("Order item not found with id: " + orderItemId));

        Extra extra = extraRepo.findById(extraId)
                .orElseThrow(() -> new RuntimeException("Extra not found with id: " + extraId));

        // Create composite key
        OrderExtraId orderExtraId = new OrderExtraId();
        orderExtraId.setOrder_item_id(orderItemId);
        orderExtraId.setExtras_id(extraId);

        // Create and save the new order extra
        OrderExtra orderExtra = new OrderExtra();
        orderExtra.setId(orderExtraId);
        orderExtra.setOrder_item(orderItem);
        orderExtra.setExtra(extra);

        orderExtraRepo.save(orderExtra);

        // Return the updated order item
        return orderItemRepo.findById(orderItemId).orElse(null);
    }

}