package com.team64.BubbleFlowBackend.controller;
import com.team64.BubbleFlowBackend.model.DrinkRecipe;
import com.team64.BubbleFlowBackend.service.DrinkRecipeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/drink-recipes")

public class DrinkRecipeController {
    @Autowired
    private DrinkRecipeService drinkRecipeService;

    @GetMapping
    public List<DrinkRecipe> getAllDrinkRecipes() {
        return drinkRecipeService.getAllDrinkRecipes();
    }

    // @PostMapping("/deleteDrinkRecipe")
    // public void deleteDrinkRecipeById(@RequestBody int drinkRecipeID) {
    //     drinkRecipeService.deleteDrinkRecipeById(drinkRecipeID);
    // }

    // @PostMapping("/addDrinkRecipe")
    // public void addDrinkRecipe(@RequestBody DrinkRecipe drinkRecipe) {
    //     drinkRecipe.setDrink_recipe_id(0); // Should be automatically generated by the database.
    //     drinkRecipeService.saveDrinkRecipe(drinkRecipe);
    // }

    // @PostMapping("/updateDrinkRecipe")
    // public void updateDrinkRecipe(@RequestBody DrinkRecipe drinkRecipe) {
    //     drinkRecipeService.updateDrinkRecipe(drinkRecipe);
    // }
}