package com.team64.BubbleFlowBackend.controller;

import com.team64.BubbleFlowBackend.model.Employee;
import com.team64.BubbleFlowBackend.service.EmployeeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import java.util.List;

@RestController
@RequestMapping("/employees")
// @CrossOrigin(origins = "*")

public class EmployeeController {

    @Autowired
    private EmployeeService employeeService;

    @GetMapping
    public List<Employee> getAllEmployees() {
        return employeeService.getAllEmployees();
    }

    @PostMapping("/deleteEmployee")
    public void deleteEmployeeById(@RequestBody int employeeID) {
        employeeService.deleteEmployeeById(employeeID);
    }

    @PostMapping("/addEmployee")
    public void addEmployee(@RequestBody Employee employee) {
        employee.setEmployee_id(0); // Should be automatically generated by the database.
        employeeService.saveEmployee(employee);
    }

    @PostMapping("/updateEmployee")
    public void updateEmployee(@RequestBody Employee employee) {
        employeeService.saveEmployee(employee);
    }
}